% A function That 

% Create this hard coded then ask deep seek to not hard code it
% I need to have 16 outcomes from this
% 4 frequency bands x 4 channels = 16
% This should be saved in wide format as a text file
% This will get uploaded to R- so the final step

function[nbchanAvgPow] = nbchanFBpow(loadedStructs, nbchanstruct, avgFB)

    % load in one struct at a time
    for strcti = 1:length(loadedStructs)

        % save channel names into a shorted variable
        currentStruct = loadedStructs(strcti);
        currentfilename = currentStruct.filename;
        chanlabl = currentStruct.chanlabl;

        % Index the chanlabl by the topographical regions
        frontalindx = ismember(chanlabl, nbchanstruct.frontal)
        temporalindx = ismember(chanlabl, nbchanstruct.temporal)
        parietalindx = ismember(chanlabl, nbchanstruct.parietal)
        occipitalindx = ismember(chanlabl, nbchanstruct.occipital)

        % Loop into the frequency bands
        for frexbndi = 1:length(avgFB)
            avgdelta_frontal = mean(currentStruct.avgdelta(frontalindx));
            avgtheta_frontal = mean(currentStruct.avgtheta(frontalindx));
            avgalpha_frontal = mean(currentStruct.avgalpha(frontalindx));
            avgbeta_frontal = mean(currentStruct.avgbeta(frontalindx));

            avgdelta_temporal = mean(currentStruct.avgdelta(temporalindx));
            avgtheta_temporal = mean(currentStruct.avgtheta(temporalindx));
            avgalpha_temporal = mean(currentStruct.avgalpha(temporalindx));
            avgbeta_temporal = mean(currentStruct.avgbeta(temporalindx));

            avgdelta_parietal = mean(currentStruct.avgdelta(parietalindx));
            avgtheta_parietal = mean(currentStruct.avgtheta(parietalindx));
            avgalpha_parietal = mean(currentStruct.avgalpha(parietalindx));
            avgbeta_parietal = mean(currentStruct.avgbeta(parietalindx));

            avgdelta_occipital = mean(currentStruct.avgdelta(occipitalindx));
            avgtheta_occipital = mean(currentStruct.avgtheta(occipitalindx));
            avgalpha_occipital = mean(currentStruct.avgalpha(occipitalindx));
            avgbeta_occipital = mean(currentStruct.avgbeta(occipitalindx));

        end

        % Create a table saving this in wide format
        table({currentfilename},...
            avgdelta_frontal, ...
            avgtheta_frontal,...
            avgalpha_frontal,...
            avgbeta_frontal,...
            avgdelta_temporal,...
            avgtheta_temporal,...
            avgalpha_temporal,...
            avgbeta_temporal,...
            avgdelta_parietal,...
            avgtheta_parietal,...
            avgalpha_parietal,...
            avgbeta_parietal,...
            avgdelta_occipital,...
            avgtheta_occipital,...
            avgalpha_occipital,...
            avgbeta_occipital,...
            'VariableNames',{
            'filename',...
            'frontal_avgdelta',...
            'frontal_avgtheta',...
            'frontal_avgalpha',...
            'frontal_avgbeta',...
            'temporal_avgdelta',...
            'temporal_avgtheta',...
            'temporal_avgalpha',...
            'temporal_avgbeta',...
            'parietal_avgdelta',...
            'parietal_avgtheta',...
            'parietal_avgalpha',...
            'parietal_avgbeta',...
            'occipital_delta',...
            'occipital_theta',...
            'occipital_alpha',...
            'occipital_beta'})
    end

end



