function data = ft_logstep(data, step_name, fun_name, cfg, stats)
%FT_LOGSTEP This function is what populates the fields generated by the
% `ft_initracker()` function. It first starts by populating information
% within the `.history` structure, such as function name, data, and the `.stats`
% structure. It then copies the `.stats` structure information into the `.summary` 
% field and renames the fields to introduce step information (aka at what step 
% was x function used).
%
% Usage
%   data = ft_logstep(data, 'robustDetrending', 'ft_robustdetrend', cfg, stats)
%
% INPUT
%   data = data (FieldTrip framework)
%   step_name = name of the function used
%   cfg = cfg structure (same as the one used for the preprocessing function)
%   stats = a stats structure with function outputs in each field

    % Check to see if cfg.preproc was nested within 'previous' by an FT function
    current_cfg = data.cfg;
    preproc_found = [];

    % Search up to 10 levels deep for `cfg.preproc`
    for depth = 1:10
        if isfield(current_cfg, 'preproc')
            preproc_found = current_cfg.preproc;
            break;
        elseif isfield(current_cfg, 'previous')
            current_cfg = current_cfg.previous;
        else
            break;  % no more previous
        end
    end

    % If cfg.preproc not present produce an error message
    if isempty(preproc_found)
        error('call the ft_inittracker() function')
    end

    % Force cfg.preproc to be at the top level
    data.cfg.preproc = preproc_found;

    % The fields that make up the `.history` structure
    step.id   = sprintf('%s_%s', step_name, datestr(now,'HHMMSSfff'));
    step.name = step_name;
    step.function = fun_name;
    step.time = datestr(now,'yyyy-mm-dd HH:MM:SS');
    step.cfg  = cfg;
    step.stats = stats;
    step.step = numel(data.cfg.preproc.history) + 1;

    % Introducing this information at the end of the existing matrix
    data.cfg.preproc.history{end+1} = step;

     % The name of the fields printed in the `.stat` (which gets copied into `.summary`
    prefix = ['s' num2str(step.step) '_' step_name '_'];

    % Renames the fields within the `.stats` structure
    fn = fieldnames(stats);
    for i = 1:numel(fn)
        data.cfg.preproc.summary.([prefix fn{i}]) = stats.(fn{i});
    end
end